# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

`Unicode-Debug`
	:runtime-requirement [ :on "perl 5.008001"^^:CpanId ];
	:test-requirement    [ :on "Test::More 0.47"^^:CpanId ];
	.
